// <auto-generated />
using System.CodeDom.Compiler;

namespace Synergy.Behaviours.Tests;

[GeneratedCode("Synergy.Behaviours.Testing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "1.0.0.0")]
public partial class CalculatorFeature
{


    [Xunit.Fact]
    // @Add
    public void AddTwoNumbers() // Scenario: Add two numbers
        => 
            Given().TheFirstNumberIs50()  // Given the first number is 50
             .And().TheSecondNumberIs70()  // And the second number is 70
            .When().TheTwoNumbersAreAdded()  // When the two numbers are added
            .Then().TheResultShouldBe120() // Then the result should be 120
            ;




}
