// <auto-generated />
using System.CodeDom.Compiler;

namespace Synergy.Behaviours.Tests.Samples;

[GeneratedCode("Synergy.Behaviours.Testing", "1.0.0.0")]
partial class CalculatorFeature
{
    private void CalculatorBackground() // Background:
    {
       Given().UserOpenedCalculator();  // Given User opened calculator
    }

    // Rule: Adding numbers

    [Xunit.Fact(DisplayName = "Scenario: Add two numbers")]
    // @Add @Verify
    public void AddTwoNumbers() // Scenario: Add two numbers
    {
       Background().CalculatorBackground();

       Given().TheFirstNumberIs50();  // Given the first number is 50
         And().TheSecondNumberIs70();  // And the second number is 70
        When().TheTwoNumbersAreAdded();  // When the two numbers are added
        Then().TheResultShouldBe120(); // Then the result should be 120

        Moreover().AfterAddTwoNumbers();
    }

    [Xunit.Fact(DisplayName = "Scenario: Add two numbers in \"different\" way")]
    // @Add
    public void AddTwoNumbersInDifferentWay() // Scenario: Add two numbers in "different" way
    {
       Background().CalculatorBackground();

       Given().TwoNumbers();  // Given Two numbers:
         And().TheFirstNumberIs50();  // * the first number is 50
         And().TheSecondNumberIs70();  // * the second number is 70
        When().TheTwoNumbersAreAdded();  // When the two numbers are added
        Then().TheResultShouldBe120(); // Then the result should be 120
    }

    // Rule: Subtracting numbers

    // Rule: Dividing numbers

    // Rule: Multiplying numbers

}
