// <auto-generated />
using System.CodeDom.Compiler;

namespace Synergy.Behaviours.Tests.Samples;

[GeneratedCode("Synergy.Behaviours.Testing", "1.0.0.0")]
partial class NewFeature // Feature: New
{
    partial void CurrentScenario(params string[] scenario);
}
